version: "3"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: parola
      MYSQL_DATABASE: flights
      MYSQL_USER: user
      MYSQL_PASSWORD: parola
    ports:
      - "33060:3306"
    networks:
      - webnet
  server:
    image: danicolescu/idp:server
    ports:
      - "5001:5001"
    networks:
      - webnet
    depends_on:
      - db
  client:
    image: danicolescu/idp:client
    ports:
      - "8888:5000"
    networks:
      - webnet
    depends_on:
      - server
networks:
  webnet:
