version: "3"
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "dbase"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    #expose:
      # Opens port 3306 on the container
      #- "3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - webnet
    deploy:
      placement:
        constraints: [node.role == manager]
  admin_db:
    image: danicolescu/idp:admin_db
    ports:
      - "5002:5002"
    networks:
      - webnet
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
  server:
    image: danicolescu/idp:server
    ports:
      - "5001:5001"
    networks:
      - webnet
    depends_on:
      - admin_db
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
  client:
    image: danicolescu/idp:client
    ports:
      - "8888:5000"
    networks:
      - webnet
    depends_on:
      - server
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
networks:
  webnet:
volumes:
  db_data:
