version: "3"
services:
  client:
    image: danicolescu/idp:client
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8888:5000"
    networks:
      - webnet
  server:
    image: danicolescu/idp:server
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"
    networks:
      - webnet
networks:
  webnet: