version: "3"
services:
  server:
    image: danicolescu/idp:server
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"
    networks:
      - webnet
  client:
    image: danicolescu/idp:client
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8888:5000"
    networks:
      - webnet
    depends_on:
      - server
networks:
  webnet:
