scrape_configs:
  - job_name: 'client_monitor'
    scrape_interval: 5s
    static_configs:
      - targets: ['client:5000']

  - job_name: 'server_monitor'
    scrape_interval: 5s
    static_configs:
      - targets: ['server:5001']